// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfN-s7UGSXb4j11wDNyhzOiJ8-a6TnIJU',
    appId: '1:769201679707:web:59ecbcb9e97373183c7e7e',
    messagingSenderId: '769201679707',
    projectId: 'flutter-chat-app-675f3',
    authDomain: 'flutter-chat-app-675f3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-675f3.firebasestorage.app',
    measurementId: 'G-NY08CF0T3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxyHz9p4WtI8H2fS-rivjLcwS0rMkpWa8',
    appId: '1:769201679707:android:473d50afd9954a7a3c7e7e',
    messagingSenderId: '769201679707',
    projectId: 'flutter-chat-app-675f3',
    storageBucket: 'flutter-chat-app-675f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZNJE9xIiFZI6j3AYf1sNkpEp_YibXiw',
    appId: '1:769201679707:ios:5181b7af3017929a3c7e7e',
    messagingSenderId: '769201679707',
    projectId: 'flutter-chat-app-675f3',
    storageBucket: 'flutter-chat-app-675f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZNJE9xIiFZI6j3AYf1sNkpEp_YibXiw',
    appId: '1:769201679707:ios:5181b7af3017929a3c7e7e',
    messagingSenderId: '769201679707',
    projectId: 'flutter-chat-app-675f3',
    storageBucket: 'flutter-chat-app-675f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfN-s7UGSXb4j11wDNyhzOiJ8-a6TnIJU',
    appId: '1:769201679707:web:7256dde8d8c4885d3c7e7e',
    messagingSenderId: '769201679707',
    projectId: 'flutter-chat-app-675f3',
    authDomain: 'flutter-chat-app-675f3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-675f3.firebasestorage.app',
    measurementId: 'G-NTVVX16MX7',
  );
}
